### ISSUE TITLE
Displays as white text, black background for me

### ISSUE THREAD

**Issue by mcandre** [stephenway/monokai.terminal#2]
I'm not seeing the usual wacky colors of Monokai using the monokai.terminal palette. It's just showing up as white text on a black background.

Could you give a screenshot of what monokai.terminal is supposed to look like?

Maybe some other Terminal.app setting is preventing the colors from showing?

System:

```
$ specs os
Specs:

specs 0.2
https://github.com/mcandre/specs#readme

system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.8.2 (12C60)
```

**Comment by dschinkel** [comment]
so..can you also update the source?  I just cloned it and same deal, it's still white.

**Comment by dschinkel** [comment]
I'm also not finding a .profile.   Using yosemite and all files are no longer hidden too.
